language: node_js
node_js:
  - '12'
install:
  - npm install -g firebase-tools
script:
  - yarn install
  - yarn build
cache:
  directories:
    - node_modules
deploy:
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    on:
      branch: master
