language: node_js
node_js:
  - '12'
branches:
  only:
    - master
install:
  - npm install -g firebase-tools
script:
  - yarn install
  - yarn build:deploy
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
