language: node_js
node_js:
  - '12'
install:
  - npm install -g codecov
  - npm install -g firebase-tools
script:
  - yarn install
  - yarn lint
  - yarn test:coverage --runInBand --no-cache
  - yarn test --runInBand --no-cache
  - codecov
cache:
  directories:
    - node_modules
deploy:
  - provider: script
    script: deploy_production.sh
    on:
      branch: master
