language: node_js
node_js:
  - '12'
install:
  - npm install -g firebase-tools
script:
  - yarn install
  - yarn build
cache:
  directories:
    - node_modules
deploy:
  - provider: script
    script: deploy_production.sh
    on:
      branch: master
