version: '2'
services:
  web:
    image: alxshelepenok/programming-for-humans:development
    build:
      context: ./
      dockerfile: Dockerfile.development
    tty: true
    volumes:
      - ./:/usr/src/app
    ports:
      - '8000:8000'
